language: node_js
node_js:
- 12
os: linux
dist: xenial
branches:
  only:
  - master
install:
- yarn
script:
- yarn test
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: x0uA3H/aulfkJ5Cl7QRfGQzaYBXp0Xo1hk9taz7W5K3EW/6O20lPsv+KcZQ+9dsYCtBlDYq8hRQPaPydq7HiwGR8vRcAVpt2hI31zJNZf8rFhSyq3LHhuQZynvXErP3BmEJ0kYZ67oTb9PRm/9VwlJ6F6hGGin4cgVsjWPxHxF9m/zFwmP1LyFzZDQA2fbB114/KSGBpBYIiN+9ltrwkKujWxapl74+eV5iRi8enlhSE9PdIHD1126IlzB3XeeCm1q8I7WgDtZDK7yg14OmCR00Nj2ZpyFk06aKPGyaW6L7jJXh7rpsrdzjelr27ZgPFOhhjRJCivfArUH6LPQrkJxHVO9ibDLBQvFlsrEofHcUYlX1UmK5ih0InUNW+97t951BWtXWYKQ3BJFfG8qVpYwlRWqQRLAFwSRsY/hkouIag0yFxYcLFvLp4KJ0GjT9qk6EJLBpdV12QXxUjKmkfReF8nXqLTWEv1TbWDdbn7+L+zD/fyD5LrXKyr3DvEKZeJQigwkocolpIrkqXUOT0R0WWWXKI18RlXN4Qaf6hukLnThmTtRy8NlS+Xqurab+M8abey7KNgGQ2un3zjz/6HCJOqm002Tp7vsmoT0aI2PNLmWLTgvdV0P8ALlr3zMg4Gfarh1MJMmUJt51JlxgCewovVbUeF64VGv9zd6d9R6o=
  app: made-up-world-nodejs
  on:
    repo: mrWD/made-up-world-nodejs
