language: node_js
node_js:
  - 12
os: linux
dist: xenial
branches:
  only:
    - master
install:
  - yarn
script:
  - yarn lint
  - yarn test
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: Ke892+oRk6ULwtMdXTQ7o2bZQMziNbPey4wYq8tIZdsGbudpI/ykbUDMKChGkSG3Tark8mUAYKqqc/ZahtQ5XozWg1sSzn2diIuTom4KIE+DnXM8bmmb/R7eRcpxbNfprZ34ppN4Zo44BLTAmkFIFo8L7UAx+VxPwOfDYXnXW/x9V79FP1psxUIbtnrW94ax1I996LkqevFYcU0kylDgRyBfNlijHYO2tNNt/mvDK7MtL0zWityP7mHuTMty9Sk4HoY6ZER/JyoIZAtMCwWCAJITc47sZ/D64QnyfI7t+xP28B5rhO8lknGPrlXD0BLmDaCd/OWpYiS7/b7BRl3UidluWKR4iDKVZ9nCyFPLN3z4MWCZtRwwXNnOeVonjxU26/czfg/zsUz088ahiLbk80bI7IJ9OMMjMjepPXs4teY3FVLYya+xZ/xYmre+5TTLYnxI5dwlrT8YNZe3Df4X6rIINoFfPsh2JVuQ2DeC9FJD9c9wBLSmZbKh1E99lBM5fXaWoCetltLz77e8qOkTxev+bgmkqOwyk2bsxI74KL+urge0qxJCXzIeYGw6XU8/8Ewv+U5uXfXSHvSgBTXBro5g7uwXqeYUJzJPZuhRx/VUo+dQVQ0Chs+pUKw/j0FjdmP2z6aoEy3mASiWEtEtAk1ZNxxtSBr5DBqcFyv8+EQ=
  app: made-up-world-nodejs
  on:
    repo: mrWD/made-up-world-nodejs
